package com.saji.stocks.candle.constants;

public enum CandleTypes {
    SPINNING_TOP,
    BULLISH_MARUBOZU, BEARISH_MARUBOZU,
    NEUTRAL_DOJI,
    GRAVESTONE_DOJI,
    BULLISH_PIN, BEARISH_PIN,


    BEARISH_ENGULFING, BULLISH_ENGULFING,
    DARK_CLOUD_COVER, PIERCING_PATTERN,
    BEARISH_HARAMI, BULLISH_HARAMI,


    EVENING_STAR, MORNING_STAR,

    BULLISH, BEARISH, MORNING_DOJI_STAR, ON_NECKLINE, BEARISH_HARAMI_CROSS,

    //    SHAVEN_BOTTOM,SHAVEN_HEAD,SHOOTING_STAR,SPINNING_TOP,
//    RISING_WINDOW,PIERCING_LINE,ON_NECKLINE,
//    MORNING_DOJI_STAR,MORNING_STAR,MARUBOZU,
    THREE_BLACK_CROWS, THREE_WHITE_SOLDIERS,
    //
//    BULLISH_3_METHOD,BULLISH_HARAMI,BULLISH_HARAMI_CROSS,BULLISH_PIN_BAR,
//    BEARISH_3_METHOD,BEARISH_HARAMI,BEARISH_HARAMI_CROSS,BEARISH_PIN_BAR,
//    BIG_DOWNWARDS,BIG_UPWARDS,
//
    LONG_LOWER_SHADOW, LONG_UPPER_SHADOW, LONG_LEGGED_DOJI,

    DARK_CLOUD, DOJI, DOJI_STAR, DRAGONFLY_DOJI,
//    INVERTED_HAMMER,HANGING_MAN,
//    GRAVESTONE_DOJI,
    //  FALLING_WINDOW,
//    EVENING_STAR,ENGULFED_BY_A_PREVIOUS,ENGULFING_A_PREVIOUS,ENGULFING_BEARISH,ENGULFING_BULLISH,EVENING_DOJI_STAR
}
