package com.saji.stocks.candle.constants;

public enum CandleTypes {
    SPINNING_TOP,
    BULLISH_MARUBOZU, BEARISH_MARUBOZU,
    NEUTRAL_DOJI, LONG_LEGGED_DOJI,
    GRAVESTONE_DOJI, DRAGONFLY_DOJI,
    BULLISH_PIN, BEARISH_PIN,


    BEARISH_ENGULFING, BULLISH_ENGULFING,
    DARK_CLOUD_COVER, PIERCING_PATTERN,
    BEARISH_HARAMI, BULLISH_HARAMI,


    EVENING_STAR, MORNING_STAR,
    THREE_WHITE_SOLDIERS, THREE_BLACK_CROWS,

    BULLISH, BEARISH
}
